security:
   encoders:
      App\Entity\Users: plaintext

   providers:
      database:
         entity:
            class: App\Entity\Users
            property: username

   firewalls:
   
      dev:
         pattern: ^/(_(profiler|wdt)|css|images|js|libs)/
         security: false
         
      main:
         pattern: ^/
         anonymous: true
         
         form_login:
            check_path: admin_login
            login_path: admin_login
            
            username_parameter: 'login[username]'
            password_parameter: 'login[password]'
            
            csrf_token_generator: security.csrf.token_manager
            default_target_path: admin
            
         logout:
            path: admin_logout
            target: admin

      
   access_control:
      - path: ^/admin/login 
        roles: IS_AUTHENTICATED_ANONYMOUSLY
      - path: ^/admin
        roles: ROLE_ADMIN
